name: SavageGenBuckets
main: net.prosavage.genbucket.GenBucket
version: 1.6.3
api-version: 1.13
authors: [ProSavage, Rages]
depend: [Factions, Vault]
softdepend: [WorldGuard]
commands:
  genbucket:
    aliases: [genbucket, gb, genshop, gen, savagegenbucket]
