# Permissions:
#   help command -> genbucket.command.help
#   reload command -> genbucket.command.admin
#   give command -> genbucket.command.give
#   menu command -> genbucket.command.menu

# Enables debug messages
debug: false

# generation shop style
generation-shop:
  background-glow: false
  # Use the 1.13 name for the item name and the plugin will automatically convert it to lower version names.
  background-item: WHITE_STAINED_GLASS_PANE
  no-lore: false
  blank-item:
    name: '&9 '
    lore:
      - '&7Click a GenBucket to buy!'
  name: "&9Genbucket Shop"
  rows: 5

# Allows liquid buckets
# WILL CAUSE LAG IF YOU HAVE WATER/LAVA FLOW ENABLED
liquid-blocks: false

# Source Block
sourceblock:
  # If this option is true, the source block will just be same type as the genbucket's block.
  # So a cobble genbucket will have a cobble sourceblock.
  no-source: false
  # Use the 1.13 name for the item name and the plugin will automatically convert it to lower version names.
  # Colors currently do not work for blocks due to the 1.13 API.
  item-name: WHITE_WOOL

# disable placing gen buckets outside own territory
canbuild-check: true
# disable gen buckets with enemies nearby
nearby-check: true
# disable placing gen buckets in protected regions
worldguard-check: true

# radius distance for nearby player check
radius: 50

# horizontal generation distance
distance: 10

# set block facing to player's direction
# fully supported on 1.13+, may also work on older versions
use-facing: false

# delay between each block being generated
# 20 equals 1 second (counting with ticks)

#####################################################
# WARNING: ANY DELAY LESS THAN 5 IS NOT RECOMMENDED #
#####################################################

delay: 10

# should genbuckets use buckets or blocks
use-bucket: true
# should genbuckets be removed from player's inventory after use,
# forcing players to buy a new one for each operation?
remove-after-use: false

# should sponge check be enabled
# cancels generation if sponge is within 3 blocks
sponge-check: false

genbucket-lore:
  - '&7Type:&4 %type%'
  - '&7Placement Price:&4 $%price%'

# blocks you want the genbuckets to override.

#########################################
# WARNING: SOLID BLOCKS NOT RECOMMENDED #
#########################################
# Use 1.13 ID's they will be converted to legacy item names automatically.
replace-blocks:
  - AIR
  - TALL_GRASS
  - LARGE_FERN
  - FERN
  - GRASS
  - POPPY

# Buckets ignore liquid blocks, helpful for repairing waterlogged bases.
replace-liquids: false

VERTICAL:
  GRAVEL:
    direction: up
    name: '&aGravel Scaffold'
    price: 200
    pseudo: true
    slot: 10
  SAND:
    direction: up
    name: '&aSand Scaffold'
    price: 5000
    pseudo: true
    slot: 13
  COBBLESTONE:
    direction: automatic
    name: '&aCobblestone Vertical'
    price: 10
    pseudo: true
    slot: 16
  OBSIDIAN:
    direction: down
    name: '&aObsidian Vertical'
    price: 1000
    pseudo: true
    slot: 19

HORIZONTAL:
  COBBLESTONE:
    name: '&aCobblestone Horizontal'
    price: 30
    pseudo: true
    slot: 22
  OBSIDIAN:
    name: '&aObsidian Horizontal'
    price: 500
    pseudo: true
    slot: 25
  NETHERRACK:
    name: '&aNetherrack Horizontal'
    price: 20
    pseudo: true
    slot: 30
  DIRT:
    name: '&aDirt Horizontal'
    price: 20
    pseudo: true
    slot: 32