name: SavageGenBuckets
main: net.prosavage.genbucket.GenBucket
version: ${project.version}
api-version: '1.13'
authors: [ProSavage, Valentina_pro, Rages]
depend: [Factions, Vault]
softdepend: [WorldGuard, SuperVanish, PremiumVanish, Essentials, FastAsyncWorldedit]
commands:
  genbucket:
    aliases: [genbucket, gb, genshop, gen, savagegenbucket]
